export const ADD_ACTIVE_TODO = "ADD_ACTIVE_TODO";
export const DELETE_ACTIVE_TODO = "DELETE_ACTIVE_TODO";
export const ADD_COMPLETED_TODO = "ADD_COMPLETED_TODO";
export const DELETE_COMPLETED_TODO = "DELETE_COMPLETED_TODO";
